import { sql, dialect, nowIso } from "./sql.js";

// The schema, written out per dialect rather than generated from a shared
// description. There are only two of them and they differ in exactly the ways
// you'd expect — identity columns, the blob type, and how a default timestamp
// is spelled. A generator that papered over that would hide the differences
// without removing them.

const SQLITE = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    token_version INTEGER NOT NULL DEFAULT 0,
    email_verified INTEGER NOT NULL DEFAULT 0,
    verify_token_hash TEXT,
    verify_token_expires TEXT,
    reset_token_hash TEXT,
    reset_token_expires TEXT,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS portfolios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    data TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'public',
    password TEXT DEFAULT '',
    views INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios(user_id);

  CREATE TABLE IF NOT EXISTS rate_limits (
    key TEXT PRIMARY KEY,
    hits INTEGER NOT NULL,
    reset_at INTEGER NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_rate_limits_reset_at ON rate_limits(reset_at);

  CREATE TABLE IF NOT EXISTS image_blobs (
    hash TEXT PRIMARY KEY,
    mime TEXT NOT NULL,
    bytes BLOB NOT NULL,
    size INTEGER NOT NULL,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS image_owners (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hash TEXT NOT NULL REFERENCES image_blobs(hash) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, hash)
  );

  CREATE INDEX IF NOT EXISTS idx_image_owners_hash ON image_owners(hash);
`;

const POSTGRES = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    token_version INTEGER NOT NULL DEFAULT 0,
    email_verified INTEGER NOT NULL DEFAULT 0,
    verify_token_hash TEXT,
    verify_token_expires TEXT,
    reset_token_hash TEXT,
    reset_token_expires TEXT,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS portfolios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    data TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'public',
    password TEXT DEFAULT '',
    views INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios(user_id);

  CREATE TABLE IF NOT EXISTS rate_limits (
    key TEXT PRIMARY KEY,
    hits INTEGER NOT NULL,
    reset_at BIGINT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_rate_limits_reset_at ON rate_limits(reset_at);

  CREATE TABLE IF NOT EXISTS image_blobs (
    hash TEXT PRIMARY KEY,
    mime TEXT NOT NULL,
    bytes BYTEA NOT NULL,
    size INTEGER NOT NULL,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS image_owners (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hash TEXT NOT NULL REFERENCES image_blobs(hash) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, hash)
  );

  CREATE INDEX IF NOT EXISTS idx_image_owners_hash ON image_owners(hash);
`;

// Existing SQLite databases predate several of these columns and were kept
// working by adding whatever was missing. Postgres gets the whole schema at
// once, so it only needs this for a database created by an older version of
// this file.
const LATE_COLUMNS = [
  ["users", "token_version", "INTEGER NOT NULL DEFAULT 0"],
  ["users", "email_verified", "INTEGER NOT NULL DEFAULT 0"],
  ["users", "verify_token_hash", "TEXT"],
  ["users", "verify_token_expires", "TEXT"],
  ["users", "reset_token_hash", "TEXT"],
  ["users", "reset_token_expires", "TEXT"],
];

async function columnsOf(table) {
  if (dialect === "postgres") {
    const rows = await sql.all("SELECT column_name AS name FROM information_schema.columns WHERE table_name = ?", [
      table,
    ]);
    return rows.map((r) => r.name);
  }
  const rows = await sql.all(`PRAGMA table_info(${table})`);
  return rows.map((r) => r.name);
}

export async function migrate() {
  await sql.exec(dialect === "postgres" ? POSTGRES : SQLITE);

  for (const [table, column, definition] of LATE_COLUMNS) {
    const existing = await columnsOf(table);
    if (!existing.includes(column)) {
      await sql.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
  }

  // created_at/updated_at used to carry a database-side default. Rows written
  // by that version are fine; this only matters for a database whose columns
  // still have the old NOT NULL with no default and no value supplied.
  await backfillTimestamps();
}

async function backfillTimestamps() {
  const stamp = nowIso();
  for (const [table, column] of [
    ["users", "created_at"],
    ["portfolios", "created_at"],
    ["portfolios", "updated_at"],
    ["image_blobs", "created_at"],
    ["image_owners", "created_at"],
  ]) {
    await sql.run(`UPDATE ${table} SET ${column} = ? WHERE ${column} IS NULL`, [stamp]).catch(() => {});
  }
}
